/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Controleurs.Creation;
import Controleurs.Lecture;
import client.lourd.nesti.Cuisiniers;
import client.lourd.nesti.Lieux;
import client.lourd.nesti.PlageHoraires;
import client.lourd.nesti.Recettes;
import client.lourd.nesti.Themes;
import client.lourd.nesti.Ville;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elrick
 */
public class CreationCours extends javax.swing.JFrame {
    int UltimeGlobalIdVille;

    /**
     *
     */
    protected static ArrayList<Recettes> lesRecettesStockées = new ArrayList<>();

    /**
     *
     */
    protected static ArrayList<PlageHoraires> lesPLagesHoraires = new ArrayList<>();

    /**
     *
     */
    protected static ArrayList<Lieux> lesLieux = new ArrayList<>();

    /**
     *
     */
    protected static ArrayList<Cuisiniers> lesCuisiniers = new ArrayList<>();
    /**
     * Creates new form CreationCours
     */
    public CreationCours() {
        initComponents();
        initTableRecettes();
        initComboPlageHoraire();
        initComboLieu();
        initTableCuisiniers();
        initComboTheme();
        initComboVille();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        createLieu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NomLieu = new javax.swing.JTextField();
        ComboVille = new javax.swing.JComboBox<>();
        ComboCP = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        ComboLieu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ComboPlageHoraire = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        anneePlage = new javax.swing.JTextField();
        moisPlage = new javax.swing.JTextField();
        jourPlage = new javax.swing.JTextField();
        heurePlage = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        minutePlage = new javax.swing.JTextField();
        créePlageHoraire = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboDuréePlage = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRecettes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableCuisiniers = new javax.swing.JTable();
        creeRecette = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        ComboTheme = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Creation Cours");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("OU");

        createLieu.setText("Créer un lieu");
        createLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLieuActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("Nom du lieu :");

        jLabel6.setText("Ville :");

        jLabel7.setText("Code postal :");

        ComboVille.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ville" }));
        ComboVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboVilleActionPerformed(evt);
            }
        });

        ComboCP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Code postal" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ComboVille, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ComboCP, 0, 97, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createLieu)
                    .addComponent(ComboVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        ComboLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboLieuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Lieu du cours :");

        jLabel16.setVisible(false);
        jLabel16.setText("Ville :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ComboLieu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Début cours :");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("OU");

        anneePlage.setEditable(false);
        anneePlage.setText("2019");
        anneePlage.setFocusable(false);

        moisPlage.setText("MM");

        jourPlage.setText("JJ");

        heurePlage.setText("HH");

        jLabel10.setText("/");

        minutePlage.setText("MM");

        créePlageHoraire.setText("Créer un horaire");
        créePlageHoraire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                créePlageHoraireActionPerformed(evt);
            }
        });

        jLabel12.setText("/");

        jLabel13.setText("/");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setText("Durée du cours :");

        comboDuréePlage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionnez une durée", "1", "2", "3", "4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(comboDuréePlage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(ComboPlageHoraire, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9)
                        .addGap(39, 39, 39)
                        .addComponent(anneePlage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moisPlage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jourPlage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(heurePlage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutePlage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(créePlageHoraire)
                        .addGap(24, 24, 24))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(anneePlage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(heurePlage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(minutePlage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(moisPlage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jourPlage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(créePlageHoraire))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(ComboPlageHoraire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(comboDuréePlage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Choix de la recette et du cuisinier :");

        tableRecettes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recettes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableRecettes);

        TableCuisiniers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Nom", "Prenom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableCuisiniers);

        creeRecette.setText("Créer le cours");
        creeRecette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creeRecetteActionPerformed(evt);
            }
        });

        annuler.setText("Annuler et quitter");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        ComboTheme.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ComboTheme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tout afficher" }));
        ComboTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboThemeActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel14.setText("Tri recettes :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(creeRecette, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboTheme, 0, 140, Short.MAX_VALUE)
                        .addGap(561, 561, 561)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ComboTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(creeRecette, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboThemeActionPerformed
        if (ComboTheme.getSelectedIndex() != 0) {
            ArrayList<Recettes> lesRecettes = Lecture.getLesRecettesSelonTheme(ComboTheme.getSelectedItem().toString());
            DefaultTableModel model = (DefaultTableModel) tableRecettes.getModel();
            if (lesRecettes != null) {
                Object[] row = new Object[1];

                if (model.getRowCount() != 0) {
                    model.setRowCount(0);
                }
                for (int i = 0; i <= lesRecettes.size() - 1; i++) {
                    Recettes uneRecette = lesRecettes.get(i);
                    row[0] = uneRecette.getNom();

                    model.addRow(row);
                }
            } else {
                if (model.getRowCount() != 0) {
                    model.setRowCount(0);
                }
            }
        }else{
            initTableRecettes();
        }
    }//GEN-LAST:event_ComboThemeActionPerformed

    private void createLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLieuActionPerformed
        boolean resultat = Creation.creationLieu(NomLieu.getText(), ComboVille.getSelectedItem().toString(), Integer.parseInt(ComboCP.getSelectedItem().toString()));
        if(resultat){
            JOptionPane.showMessageDialog(null, "Lieu crée, ajouté a la liste de lieux sur la gauche.", "Bravo !", 2);
            ComboLieu.removeAllItems();
            initComboLieu();
            resetAprèsCreation();
        }else{
            JOptionPane.showMessageDialog(null, "Lieu non créé, verifiez votre saisie.", "ERROR", 2);
        }
        
    }//GEN-LAST:event_createLieuActionPerformed

    private void ComboVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboVilleActionPerformed
        if (ComboVille.getSelectedIndex() != 0) {
            Object villeSelectionnee = ComboVille.getSelectedItem();

            String coucou = villeSelectionnee.toString();
            ArrayList<Ville> lesVilles = Lecture.getLesCP(coucou);

            if (ComboCP.getItemCount() != 1) {
                ComboCP.removeAllItems();
                ComboCP.addItem("CP");
            }
            for (int i = 0; i <= lesVilles.size() - 1; i++) {
                Ville uneVille = lesVilles.get(i);

                ComboCP.addItem(Integer.toString(uneVille.getCodePostal()));
                if (UltimeGlobalIdVille != uneVille.getId()) {
                    UltimeGlobalIdVille = uneVille.getId();
                }
            }
        }
    }//GEN-LAST:event_ComboVilleActionPerformed

    private void créePlageHoraireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_créePlageHoraireActionPerformed
        String plageHoraire = anneePlage.getText() + "-" + moisPlage.getText()+"-"+jourPlage.getText()+" "+heurePlage.getText()+":"+minutePlage.getText()+":00";
        if(Creation.creationHoraire(plageHoraire)){
            JOptionPane.showMessageDialog(null, "Plage horaire crée, ajoutée a la liste sur la gauche.", "Bravo !", 2);
            ComboPlageHoraire.removeAllItems();
            initComboPlageHoraire();
            resetAprèsCreation();
        }else{
            JOptionPane.showMessageDialog(null, "Plage horaire non créée, verifiez votre saisie.", "ERROR", 2);
        }
    }//GEN-LAST:event_créePlageHoraireActionPerformed

    private void creeRecetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creeRecetteActionPerformed
        if(Creation.creationCours(tableRecettes.getValueAt(tableRecettes.getSelectedRow(), 0).toString(), Integer.parseInt(TableCuisiniers.getValueAt(TableCuisiniers.getSelectedRow(), 0).toString()), ComboLieu.getSelectedItem().toString(),jLabel17.getText(), ComboPlageHoraire.getSelectedItem().toString(), Integer.parseInt(comboDuréePlage.getSelectedItem().toString()))){
            JOptionPane.showMessageDialog(jPanel1, "Cours créé avec succès. Pas de doublon, pas de problème, génial...", "Bravo !", 2);
    }else{
            JOptionPane.showMessageDialog(jPanel1, "Un doublon du cours existe (possiblement un cuisinier qui as deux cours au meme moment ?)", "Dommage !", 2);
        }
    }//GEN-LAST:event_creeRecetteActionPerformed

    private void ComboLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboLieuActionPerformed
        
        if(ComboLieu.getSelectedIndex() != 0){
            Lieux selectedLieu = lesLieux.get(ComboLieu.getSelectedIndex()-1);
            jLabel16.setVisible(true);
            jLabel17.setText(selectedLieu.getVille().getNom());
        }else{
            jLabel16.setVisible(false);
            jLabel17.setText("");
        }
        

    }//GEN-LAST:event_ComboLieuActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        resetTotal();
        this.dispose();
    }//GEN-LAST:event_annulerActionPerformed

    private void initTableRecettes(){
        lesRecettesStockées = Lecture.getLesRecettes();
        DefaultTableModel model = (DefaultTableModel) tableRecettes.getModel();
        Object[] row = new Object[1];

        if (model.getRowCount() != 0) {
            model.setRowCount(0);
        }

        for (int i = 0; i <= lesRecettesStockées.size() - 1; i++) {
            Recettes uneRecettes = lesRecettesStockées.get(i);
            row[0] = uneRecettes.getNom();

            model.addRow(row);
        }
    }
    private void initComboPlageHoraire(){
        lesPLagesHoraires = Lecture.getLesPlagesHoraires();
        ComboPlageHoraire.addItem("Selectionnez une plage horaire !");
        for (int i = 0; i <= lesPLagesHoraires.size() - 1; i++) {
            PlageHoraires unePlage = lesPLagesHoraires.get(i);
            ComboPlageHoraire.addItem(unePlage.getDate());
        }
    }
    private void initComboLieu(){
        lesLieux = Lecture.getLesLieux();
        ComboLieu.addItem("Selectionnez un lieu !");
        for (int i = 0; i <= lesLieux.size() - 1; i++) {
            Lieux unLieu = lesLieux.get(i);
            ComboLieu.addItem(unLieu.getNom());
        }
    }
    private void initTableCuisiniers(){
        lesCuisiniers = Lecture.getLesCuisiniers();
        DefaultTableModel model = (DefaultTableModel) TableCuisiniers.getModel();
        Object[] row = new Object[3];

        if (model.getRowCount() != 0) {
            model.setRowCount(0);
        }

        for (int i = 0; i <= lesCuisiniers.size() - 1; i++) {
            Cuisiniers unCuisinier = lesCuisiniers.get(i);
            row[0] = unCuisinier.getID();
            row[1] = unCuisinier.getNom();
            row[2] = unCuisinier.getPrenom();

            model.addRow(row);
        }
    }
    private void initComboTheme(){
        ArrayList<Themes> lesThemes = Lecture.getLesThemes();

        for (int i = 0; i <= lesThemes.size() - 1; i++) {
            Themes unTheme = lesThemes.get(i);
            ComboTheme.addItem(unTheme.getName());
        }
    }
    private void initComboVille(){
        ArrayList<Ville> lesVilles = Lecture.getLesVilles();
        for (int i = 0; i <= lesVilles.size() - 1; i++) {
            Ville uneVille = lesVilles.get(i);
            ComboVille.addItem(uneVille.getNom());
        }
    }
    private void resetAprèsCreation(){
        ComboVille.setSelectedIndex(0);
        ComboCP.setSelectedIndex(0);
        NomLieu.setText("");    
        moisPlage.setText("MM");
        jourPlage.setText("JJ");
        heurePlage.setText("HH");
        minutePlage.setText("MM");
    }
    private void resetTotal(){
        ComboVille.setSelectedIndex(0);
        ComboCP.setSelectedIndex(0);
        NomLieu.setText("");    
        moisPlage.setText("MM");
        jourPlage.setText("JJ");
        heurePlage.setText("HH");
        minutePlage.setText("MM");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreationCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreationCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreationCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreationCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreationCours().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCP;
    private javax.swing.JComboBox<String> ComboLieu;
    private javax.swing.JComboBox<String> ComboPlageHoraire;
    private javax.swing.JComboBox<String> ComboTheme;
    private javax.swing.JComboBox<String> ComboVille;
    private javax.swing.JTextField NomLieu;
    private javax.swing.JTable TableCuisiniers;
    private javax.swing.JTextField anneePlage;
    private javax.swing.JButton annuler;
    private javax.swing.JComboBox<String> comboDuréePlage;
    private javax.swing.JButton createLieu;
    private javax.swing.JButton creeRecette;
    private javax.swing.JButton créePlageHoraire;
    private javax.swing.JTextField heurePlage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jourPlage;
    private javax.swing.JTextField minutePlage;
    private javax.swing.JTextField moisPlage;
    private javax.swing.JTable tableRecettes;
    // End of variables declaration//GEN-END:variables
}
